[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
]
ffi = true #con esto estas diciendo que estas permitiendo foundry corra comandos directamente en tu terminal
# lo mas recomendable que esto este en false. 


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
